### ISSUE TITLE
im not able to install pyaudio in pt\ython 3.9

### ISSUE THREAD

**Issue by Bhanu-tarun** [try2catch/SELF_LEARNING_JARVIS_AI#1]

**Comment by try2catch** [comment]
Bro, no one can help you by just having information that you have issues. Please share the exact issue or details of the issues.

**Comment by Bhanu-tarun** [comment]
ok bro, i will share the info. actually i thought i did that day and i
left, but i didnt.

**Comment by try2catch** [comment]
It seems you are on windows. if I am correct then try the below command and let me know if you are not able to install the pyaudio. Make sure to install/run the command in the the environment which you are using for your project.
pip install pipwin
pipwin install pyaudio

**Comment by Bhanu-tarun** [comment]
Sorry very much, I didint open the computer for a while. here is the thing
I got when i tried. I use kali linux (debian based)

through the add button in the settings.
Collecting PyAudio
  Using cached PyAudio-0.2.11.tar.gz (37 kB)
Building wheels for collected packages: PyAudio
  Building wheel for PyAudio (setup.py): started
  Building wheel for PyAudio (setup.py): finished with status 'error'
  Running setup.py clean for PyAudio
Failed to build PyAudio
Installing collected packages: PyAudio
    Running setup.py install for PyAudio: started
    Running setup.py install for PyAudio: finished with status 'error'

  ERROR: Command errored out with exit status 1:
   command: /home/takak/PycharmProjects/ChibiAI/venv/bin/python -u -c
'import sys, setuptools, tokenize; sys.argv[0] =
'"'"'/tmp/pip-install-mthu2boy/pyaudio_6f7856c780984ff7a7584657c26996af/setup.py'"'"';
__file__='"'"'/tmp/pip-install-mthu2boy/pyaudio_6f7856c780984ff7a7584657c26996af/setup.py'"'"';f=getattr(tokenize,
'"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"',
'"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
bdist_wheel -d /tmp/pip-wheel-se0rnytv
       cwd:
/tmp/pip-install-mthu2boy/pyaudio_6f7856c780984ff7a7584657c26996af/
  Complete output (18 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.9
  copying src/pyaudio.py -> build/lib.linux-x86_64-3.9
  warning: build_py: byte-compiling is disabled, skipping.

  running build_ext
  building '_portaudio' extension
  creating build/temp.linux-x86_64-3.9
  creating build/temp.linux-x86_64-3.9/src
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG
-g -fwrapv -O2 -Wall -g
-ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=.
-fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g
-ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=.
-fstack-protector-strong -Wformat -Werror=format-security -Wdate-time
-D_FORTIFY_SOURCE=2 -fPIC
-I/home/takak/PycharmProjects/ChibiAI/venv/include -I/usr/include/python3.9
-c src/_portaudiomodule.c -o
build/temp.linux-x86_64-3.9/src/_portaudiomodule.o
  src/_portaudiomodule.c:29:10: fatal error: portaudio.h: No such file or
directory
     29 | #include "portaudio.h"
        |          ^~~~~~~~~~~~~
  compilation terminated.
  error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for PyAudio
    ERROR: Command errored out with exit status 1:
     command: /home/takak/PycharmProjects/ChibiAI/venv/bin/python -u -c
'import sys, setuptools, tokenize; sys.argv[0] =
'"'"'/tmp/pip-install-mthu2boy/pyaudio_6f7856c780984ff7a7584657c26996af/setup.py'"'"';
__file__='"'"'/tmp/pip-install-mthu2boy/pyaudio_6f7856c780984ff7a7584657c26996af/setup.py'"'"';f=getattr(tokenize,
'"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"',
'"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
install --record /tmp/pip-record-hfrvki5u/install-record.txt
--single-version-externally-managed --compile --install-headers
/home/takak/PycharmProjects/ChibiAI/venv/include/site/python3.9/PyAudio
         cwd:
/tmp/pip-install-mthu2boy/pyaudio_6f7856c780984ff7a7584657c26996af/
    Complete output (18 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.9
    copying src/pyaudio.py -> build/lib.linux-x86_64-3.9
    warning: build_py: byte-compiling is disabled, skipping.

    running build_ext
    building '_portaudio' extension
    creating build/temp.linux-x86_64-3.9
    creating build/temp.linux-x86_64-3.9/src
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare
-DNDEBUG -g -fwrapv -O2 -Wall -g
-ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=.
-fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g
-ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=.
-fstack-protector-strong -Wformat -Werror=format-security -Wdate-time
-D_FORTIFY_SOURCE=2 -fPIC
-I/home/takak/PycharmProjects/ChibiAI/venv/include -I/usr/include/python3.9
-c src/_portaudiomodule.c -o
build/temp.linux-x86_64-3.9/src/_portaudiomodule.o
    src/_portaudiomodule.c:29:10: fatal error: portaudio.h: No such file or
directory
       29 | #include "portaudio.h"
          |          ^~~~~~~~~~~~~
    compilation terminated.
    error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1:
/home/takak/PycharmProjects/ChibiAI/venv/bin/python -u -c 'import sys,
setuptools, tokenize; sys.argv[0] =
'"'"'/tmp/pip-install-mthu2boy/pyaudio_6f7856c780984ff7a7584657c26996af/setup.py'"'"';
__file__='"'"'/tmp/pip-install-mthu2boy/pyaudio_6f7856c780984ff7a7584657c26996af/setup.py'"'"';f=getattr(tokenize,
'"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"',
'"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
install --record /tmp/pip-record-hfrvki5u/install-record.txt
--single-version-externally-managed --compile --install-headers
/home/takak/PycharmProjects/ChibiAI/venv/include/site/python3.9/PyAudio
Check the logs for full command output.

and by typing in terminal:
Collecting PyAudio
  Using cached PyAudio-0.2.11.tar.gz (37 kB)
Building wheels for collected packages: PyAudio
  Building wheel for PyAudio (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/takak/PycharmProjects/ChibiAI/venv/bin/python -u -c
'import sys, setuptools, tokenize; sys.argv[0] =
'"'"'/tmp/pip-install-7o4pmn2r/pyaudio_04d29f47a0494080ab3fd42f83555ca3/setup.py'"'"';
__file__='"'"'/tmp/pip-install-7o4pmn2r/pyaudio_04d29f47a0494080ab3fd42f83555ca3/setup.py'"'"';f=getattr(tokenize,
'"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"',
'"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
bdist_wheel -d /tmp/pip-wheel-chh6otdz
       cwd:
/tmp/pip-install-7o4pmn2r/pyaudio_04d29f47a0494080ab3fd42f83555ca3/
  Complete output (16 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.9
  copying src/pyaudio.py -> build/lib.linux-x86_64-3.9
  running build_ext
  building '_portaudio' extension
  creating build/temp.linux-x86_64-3.9
  creating build/temp.linux-x86_64-3.9/src
  x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG
-g -fwrapv -O2 -Wall -g
-ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=.
-fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g
-ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=.
-fstack-protector-strong -Wformat -Werror=format-security -Wdate-time
-D_FORTIFY_SOURCE=2 -fPIC
-I/home/takak/PycharmProjects/ChibiAI/venv/include -I/usr/include/python3.9
-c src/_portaudiomodule.c -o
build/temp.linux-x86_64-3.9/src/_portaudiomodule.o
  src/_portaudiomodule.c:29:10: fatal error: portaudio.h: No such file or
directory
     29 | #include "portaudio.h"
        |          ^~~~~~~~~~~~~
  compilation terminated.
  error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for PyAudio
  Running setup.py clean for PyAudio
Failed to build PyAudio
Installing collected packages: PyAudio
    Running setup.py install for PyAudio ... error
    ERROR: Command errored out with exit status 1:
     command: /home/takak/PycharmProjects/ChibiAI/venv/bin/python -u -c
'import sys, setuptools, tokenize; sys.argv[0] =
'"'"'/tmp/pip-install-7o4pmn2r/pyaudio_04d29f47a0494080ab3fd42f83555ca3/setup.py'"'"';
__file__='"'"'/tmp/pip-install-7o4pmn2r/pyaudio_04d29f47a0494080ab3fd42f83555ca3/setup.py'"'"';f=getattr(tokenize,
'"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"',
'"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
install --record /tmp/pip-record-ety31q73/install-record.txt
--single-version-externally-managed --compile --install-headers
/home/takak/PycharmProjects/ChibiAI/venv/include/site/python3.9/PyAudio
         cwd:
/tmp/pip-install-7o4pmn2r/pyaudio_04d29f47a0494080ab3fd42f83555ca3/
    Complete output (16 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.9
    copying src/pyaudio.py -> build/lib.linux-x86_64-3.9
    running build_ext
    building '_portaudio' extension
    creating build/temp.linux-x86_64-3.9
    creating build/temp.linux-x86_64-3.9/src
    x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare
-DNDEBUG -g -fwrapv -O2 -Wall -g
-ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=.
-fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g
-ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=.
-fstack-protector-strong -Wformat -Werror=format-security -Wdate-time
-D_FORTIFY_SOURCE=2 -fPIC
-I/home/takak/PycharmProjects/ChibiAI/venv/include -I/usr/include/python3.9
-c src/_portaudiomodule.c -o
build/temp.linux-x86_64-3.9/src/_portaudiomodule.o
    src/_portaudiomodule.c:29:10: fatal error: portaudio.h: No such file or
directory
       29 | #include "portaudio.h"
          |          ^~~~~~~~~~~~~
    compilation terminated.
    error: command '/usr/bin/x86_64-linux-gnu-gcc' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1:
/home/takak/PycharmProjects/ChibiAI/venv/bin/python -u -c 'import sys,
setuptools, tokenize; sys.argv[0] =
'"'"'/tmp/pip-install-7o4pmn2r/pyaudio_04d29f47a0494080ab3fd42f83555ca3/setup.py'"'"';
__file__='"'"'/tmp/pip-install-7o4pmn2r/pyaudio_04d29f47a0494080ab3fd42f83555ca3/setup.py'"'"';f=getattr(tokenize,
'"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"',
'"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
install --record /tmp/pip-record-ety31q73/install-record.txt
--single-version-externally-managed --compile --install-headers
/home/takak/PycharmProjects/ChibiAI/venv/include/site/python3.9/PyAudio
Check the logs for full command output.

**Comment by try2catch** [comment]
Make sure to install/run the command in the the environment which you are using for your project.
pip install pipwin
pipwin install pyaudio
